extends: default

rules:
  line-length:
    max: 120
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  trailing-spaces: enable
  new-line-at-end-of-file: enable