name: 🐛 Bug Report
description: Report a bug to help us improve Ownfoil
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please ensure you've completed these steps before submitting
      options:
        - label: I have searched existing issues to make sure this bug hasn't been reported already
          required: true
        - label: I have read the [README](https://github.com/samuelcaldas/ownfoil/blob/master/README.md) and checked the documentation
          required: true
        - label: I am using the latest version of Ownfoil
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install Ownfoil?
      options:
        - Docker (docker run)
        - Docker Compose
        - Python (direct installation)
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Ownfoil Version
      description: What version of Ownfoil are you running?
      placeholder: "e.g., v1.2.3 or latest"
    validations:
      required: true

  - type: input
    id: docker-version
    attributes:
      label: Docker Version (if applicable)
      description: If using Docker, what version are you running?
      placeholder: "e.g., 24.0.6"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL/Fedora)
        - Linux (Arch)
        - Linux (Other)
        - Windows 10/11
        - Windows Server
        - macOS
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser (for web interface issues)
      description: What browser are you using when the issue occurs?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other (please specify)
        - Not applicable

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please provide relevant logs, error messages, or console output
      placeholder: |
        Paste any relevant logs here. You can get Docker logs with:
        docker logs <container_name>
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share relevant configuration (remove any sensitive information)
      placeholder: |
        Share your docker-compose.yml, environment variables, or settings that might be relevant
        Remember to remove sensitive information like passwords, API keys, etc.
      render: yaml
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here or use the attachment button

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help us understand the issue

  - type: checkboxes
    id: contributing
    attributes:
      label: Contributing
      options:
        - label: I would be willing to submit a pull request to fix this issue
          required: false