blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/samuelcaldas/ownfoil/blob/master/README.md
    about: Read the documentation before opening an issue
  - name: 💬 Discussions
    url: https://github.com/samuelcaldas/ownfoil/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/samuelcaldas/ownfoil/security/advisories/new
    about: Report security vulnerabilities privately