name: Publish multi arch Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    if: "!startsWith(github.ref, 'refs/heads/dependabot') && !startsWith(github.event.head_commit.message, 'ci') && !startsWith(github.event.head_commit.message, 'doc')"
    runs-on: ubuntu-latest
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: samuelcaldas/ownfoil
          flavor: |
            latest=auto
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch,enable=${{ github.ref != 'refs/heads/master' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title={{.Name}}
            org.opencontainers.image.description=Nintendo Switch library manager and self-hosted Tinfoil Shop
            org.opencontainers.image.url=https://github.com/samuelcaldas/ownfoil
            org.opencontainers.image.source=https://github.com/samuelcaldas/ownfoil
            org.opencontainers.image.version={{.Version}}
            org.opencontainers.image.created={{.Date}}
            org.opencontainers.image.revision={{.FullCommit}}
            org.opencontainers.image.licenses=MIT

      - name: Set platforms based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "PLATFORMS=linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6" >> $GITHUB_ENV
          else
            echo "PLATFORMS=linux/amd64,linux/arm64" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true
