name: Build multi arch Docker image on PR

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - 'app/**'
      - 'docker/**'
      - '.github/workflows/docker_pr.yml'

permissions:
  contents: read
  security-events: write

jobs:
  build_docker_pr:
    name: Build multi arch Docker image on PR
    runs-on: ubuntu-latest
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: samuelcaldas/ownfoil
          tags: |
            type=ref,event=pr
          labels: |
            org.opencontainers.image.title=ownfoil
            org.opencontainers.image.description=Nintendo Switch library manager and self-hosted Tinfoil Shop
            org.opencontainers.image.url=https://github.com/samuelcaldas/ownfoil
            org.opencontainers.image.source=https://github.com/samuelcaldas/ownfoil

      - name: Build Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max